-- ─── REPORTFLOW SUPABASE DATABASE SCHEMA ──────────────────────────────────
-- Run this script in the Supabase Dashboard -> SQL Editor

-- 1. Create Members Table
CREATE TABLE IF NOT EXISTS public.members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'Staff Member',
    department TEXT NOT NULL DEFAULT 'Engineering',
    compliance INTEGER NOT NULL DEFAULT 95,
    initials TEXT NOT NULL DEFAULT 'US',
    color TEXT NOT NULL DEFAULT '#005030',
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Reports Table
CREATE TABLE IF NOT EXISTS public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    department TEXT NOT NULL,
    type TEXT NOT NULL, -- 'Daily', 'Weekly', 'Monthly', 'Quarterly', 'Yearly'
    status TEXT NOT NULL DEFAULT 'Draft', -- 'Draft', 'Submitted', 'Approved', 'Flagged'
    summary TEXT,
    feedback TEXT,
    gve_kuka_data JSONB,
    gve_weekly_data JSONB,
    gve_quarterly_data JSONB,
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- 4. Create Public Access Policies (Allow authenticated & anon read/write for app client)
CREATE POLICY "Allow public read access to members" ON public.members FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update to members" ON public.members FOR ALL USING (true);

CREATE POLICY "Allow public read access to reports" ON public.reports FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update/delete to reports" ON public.reports FOR ALL USING (true);

-- 5. Enable Realtime Replication (so changes appear instantly without refreshing)
ALTER PUBLICATION supabase_realtime ADD TABLE public.reports;
ALTER PUBLICATION supabase_realtime ADD TABLE public.members;

