import { Report } from "../types/report"
import { Member } from "../types/member"
import { Deadline } from "../types/deadline"
import { createEmptyGveQuarterlyData } from "../types/gveQuarterly"

export const DEPARTMENTS = [
  "All",
  "Engineering",
  "Marketing",
  "Finance",
  "Operations",
  "HR",
  "Sales",
  "Legal",
]

export const DEFAULT_DEADLINES: Deadline[] = [
  {
    id: 1,
    title: "Weekly Site Operational Log",
    department: "Engineering",
    dueDate: "2026-08-28",
    priority: "High",
    description:
      "Submission of all 12-hour solar PV, inverter remarks, and battery bank parameters.",
  },
  {
    id: 2,
    title: "Q3 Facility & Safety Audit",
    department: "Operations",
    dueDate: "2026-08-30",
    priority: "Medium",
    description: "Quarterly inspection of fire suppression and earthing grids.",
  },
  {
    id: 3,
    title: "Monthly Capex & Field Reconciliation",
    department: "Finance",
    dueDate: "2026-08-31",
    priority: "High",
    description:
      "Reconciliation of site diesel procurement and technician allowances.",
  },
  {
    id: 4,
    title: "Monthly Performance & KPI Review",
    department: "All Departments",
    dueDate: "2026-08-31",
    priority: "Medium",
    description:
      "General monthly reporting cycle across all departmental teams.",
  },
]

export const MEMBERS: Member[] = [
  {
    id: 99,
    name: "GVE Operations Lead",
    email: "info@gve-group.com",
    role: "Super Administrator",
    department: "Management",
    lastReport: new Date("2026-09-27"),
    compliance: 100,
    initials: "GV",
    color: "#005030",
    isAdmin: true,
  },
  {
    id: 1,
    name: "Amara Osei",
    email: "amara.osei@gve-group.com",
    role: "Senior Engineer",
    department: "Engineering",
    lastReport: new Date("2026-07-27"),
    compliance: 98,
    initials: "AO",
    color: "#005030",
    isAdmin: false,
  },
  {
    id: 2,
    name: "Lena Brandt",
    email: "lena.brandt@gve-group.com",
    role: "Marketing Lead",
    department: "Marketing",
    lastReport: new Date("2026-07-24T00:00:00Z"),
    compliance: 92,
    initials: "LB",
    color: "#1a5c40",
    isAdmin: false,
  },
  {
    id: 3,
    name: "Marcus Chen",
    email: "marcus.chen@gve-group.com",
    role: "Ops Manager",
    department: "Operations",
    lastReport: new Date("2026-07-27T00:00:00Z"),
    compliance: 100,
    initials: "MC",
    color: "#005030",
    isAdmin: true,
  },
  {
    id: 4,
    name: "Priya Nair",
    email: "priya.nair@gve-group.com",
    role: "Finance Director",
    department: "Finance",
    lastReport: new Date("2026-07-22T00:00:00Z"),
    compliance: 87,
    initials: "PN",
    color: "#7a4010",
    isAdmin: false,
  },
  {
    id: 5,
    name: "James Okafor",
    email: "james.okafor@gve-group.com",
    role: "HR Manager",
    department: "HR",
    lastReport: new Date("2026-07-23T00:00:00Z"),
    compliance: 95,
    initials: "JO",
    color: "#1a5c40",
    isAdmin: false,
  },
  {
    id: 6,
    name: "Sofia Alvarez",
    email: "sofia.alvarez@gve-group.com",
    role: "Staff Engineer",
    department: "Engineering",
    lastReport: new Date("2026-07-27T00:00:00Z"),
    compliance: 90,
    initials: "SA",
    color: "#005030",
    isAdmin: false,
  },
  {
    id: 7,
    name: "Daniel Ruiz",
    email: "daniel.ruiz@gve-group.com",
    role: "Account Executive",
    department: "Sales",
    lastReport: new Date("2026-07-25T00:00:00Z"),
    compliance: 96,
    initials: "DR",
    color: "#1a5c40",
    isAdmin: false,
  },
  {
    id: 8,
    name: "Yuki Tanaka",
    email: "yuki.tanaka@gve-group.com",
    role: "Legal Counsel",
    department: "Legal",
    lastReport: new Date("2026-07-20T00:00:00Z"),
    compliance: 100,
    initials: "YT",
    color: "#005030",
    isAdmin: false,
  },
  {
    id: 9,
    name: "Felix Wagner",
    email: "felix.wagner@gve-group.com",
    role: "Backend Engineer",
    department: "Engineering",
    lastReport: new Date("2026-07-26T00:00:00Z"),
    compliance: 83,
    initials: "FW",
    color: "#7a4010",
    isAdmin: false,
  },
  {
    id: 10,
    name: "Chioma Eze",
    email: "chioma.eze@gve-group.com",
    role: "Brand Designer",
    department: "Marketing",
    lastReport: new Date("2026-07-25T00:00:00Z"),
    compliance: 91,
    initials: "CE",
    color: "#1a5c40",
    isAdmin: false,
  },
  {
    id: 11,
    name: "Raj Mehta",
    email: "raj.mehta@gve-group.com",
    role: "Data Analyst",
    department: "Finance",
    lastReport: new Date("2026-07-24T00:00:00Z"),
    compliance: 94,
    initials: "RM",
    color: "#005030",
    isAdmin: false,
  },
  {
    id: 12,
    name: "Nadia Kowalski",
    email: "nadia.kowalski@gve-group.com",
    role: "Recruiter",
    department: "HR",
    lastReport: new Date("2026-07-22T00:00:00Z"),
    compliance: 88,
    initials: "NK",
    color: "#1a5c40",
    isAdmin: false,
  },
]

export const REPORTS: Report[] = [
  {
    id: 1,
    title: "GVE KUKA Site Hourly Record — Jul 27",
    author: "Amara Osei",
    department: "Engineering",
    type: "Daily",
    submitted: new Date("2026-07-27T00:00:00Z"),
    status: "Approved",
    summary:
      "Official physical GVE KUKA Site Operational Hourly Record sheet filled out with 12-hour solar PV, battery storage, site load, and grid parameters.",
    gveData: {
      siteName: "GVE KUKA SITE",
      title: "GVE KUKA Site Hourly Record",
      date: "2026-07-27",
      day: "Monday",
      year: "2026",
      entries: [
        {
          id: "e1",
          time: "06:00 AM",
          pv: { volt: "420", curr: "12.5", power: "5.25", energy: "5.25" },
          battery: { volt: "51.2", curr: "24.0", soc: "85", soh: "99" },
          load: {
            l1_v: "230",
            l1_a: "8.5",
            l2_v: "231",
            l2_c: "8.2",
            l3_v: "229",
            l3_c: "8.4",
            power: "5.8",
            energy: "5.8",
          },
          grid: {
            l1_v: "0",
            l1_a: "0",
            l2_v: "0",
            l2_c: "0",
            l3_v: "0",
            l3_c: "0",
            power: "0",
            energy: "0",
          },
          spd: { in: "GOOD", out: "GOOD" },
          cooling: { ac1: "ON", ac2: "ON" },
          operatorName: "Amara Osei",
        },
        {
          id: "e2",
          time: "07:00 AM",
          pv: { volt: "435", curr: "18.2", power: "7.91", energy: "13.16" },
          battery: { volt: "52.0", curr: "31.5", soc: "90", soh: "99" },
          load: {
            l1_v: "230",
            l1_a: "9.1",
            l2_v: "230",
            l2_c: "9.0",
            l3_v: "231",
            l3_c: "8.9",
            power: "6.2",
            energy: "12.0",
          },
          grid: {
            l1_v: "0",
            l1_a: "0",
            l2_v: "0",
            l2_c: "0",
            l3_v: "0",
            l3_c: "0",
            power: "0",
            energy: "0",
          },
          spd: { in: "GOOD", out: "GOOD" },
          cooling: { ac1: "ON", ac2: "ON" },
          operatorName: "Amara Osei",
        },
        {
          id: "e3",
          time: "08:00 AM",
          pv: { volt: "450", curr: "25.0", power: "11.25", energy: "24.41" },
          battery: { volt: "53.5", curr: "42.0", soc: "96", soh: "99" },
          load: {
            l1_v: "231",
            l1_a: "11.0",
            l2_v: "231",
            l2_c: "10.8",
            l3_v: "230",
            l3_c: "11.2",
            power: "7.6",
            energy: "19.6",
          },
          grid: {
            l1_v: "0",
            l1_a: "0",
            l2_v: "0",
            l2_c: "0",
            l3_v: "0",
            l3_c: "0",
            power: "0",
            energy: "0",
          },
          spd: { in: "GOOD", out: "GOOD" },
          cooling: { ac1: "ON", ac2: "ON" },
          operatorName: "Amara Osei",
        },
        {
          id: "e4",
          time: "09:00 AM",
          pv: { volt: "460", curr: "30.4", power: "13.98", energy: "38.39" },
          battery: { volt: "54.1", curr: "15.0", soc: "100", soh: "99" },
          load: {
            l1_v: "230",
            l1_a: "14.2",
            l2_v: "229",
            l2_c: "14.0",
            l3_v: "230",
            l3_c: "14.1",
            power: "9.7",
            energy: "29.3",
          },
          grid: {
            l1_v: "0",
            l1_a: "0",
            l2_v: "0",
            l2_c: "0",
            l3_v: "0",
            l3_c: "0",
            power: "0",
            energy: "0",
          },
          spd: { in: "GOOD", out: "GOOD" },
          cooling: { ac1: "ON", ac2: "ON" },
          operatorName: "Amara Osei",
        },
        {
          id: "e5",
          time: "10:00 AM",
          pv: { volt: "465", curr: "32.1", power: "14.92", energy: "53.31" },
          battery: { volt: "54.2", curr: "5.0", soc: "100", soh: "99" },
          load: {
            l1_v: "230",
            l1_a: "16.0",
            l2_v: "231",
            l2_c: "15.8",
            l3_v: "230",
            l3_c: "16.1",
            power: "11.0",
            energy: "40.3",
          },
          grid: {
            l1_v: "0",
            l1_a: "0",
            l2_v: "0",
            l2_c: "0",
            l3_v: "0",
            l3_c: "0",
            power: "0",
            energy: "0",
          },
          spd: { in: "GOOD", out: "GOOD" },
          cooling: { ac1: "ON", ac2: "ON" },
          operatorName: "Amara Osei",
        },
      ],
    },
  },
  {
    id: 2,
    title: "Campaign Performance — July",
    author: "Lena Brandt",
    department: "Marketing",
    type: "Monthly",
    submitted: new Date("2026-07-24T00:00:00Z"),
    status: "Submitted",
    summary:
      "Email open rate at 31.4%, up from 27.1% in June. LinkedIn ad spend delivered 14% lower CPL. Retargeting cohort underperforming — recommend budget reallocation.",
  },
  {
    id: 3,
    title: "Daily Ops Standup — Jul 27",
    author: "Marcus Chen",
    department: "Operations",
    type: "Daily",
    submitted: new Date("2026-07-27T00:00:00Z"),
    status: "Approved",
    summary:
      "Fulfillment at 98.2% on-time. One supplier delay flagged for packaging materials — estimated 3-day impact. Escalated to procurement.",
  },
  {
    id: 4,
    title: "H1 Budget Reconciliation",
    author: "Priya Nair",
    department: "Finance",
    type: "Yearly",
    submitted: new Date("2026-07-22T00:00:00Z"),
    status: "Flagged",
    summary:
      "Variance of $142k identified in Engineering capex line. Pending clarification from department heads. CFO review scheduled Jul 30.",
  },
  {
    id: 5,
    title: "Talent Pipeline — July",
    author: "James Okafor",
    department: "HR",
    type: "Monthly",
    submitted: new Date("2026-07-23T00:00:00Z"),
    status: "Submitted",
    summary:
      "7 open roles across Engineering and Sales. Offer acceptance rate at 88%. Two senior hires in final-round interviews.",
  },
  {
    id: 6,
    title: "Deployment Log — Jul 27",
    author: "Sofia Alvarez",
    department: "Engineering",
    type: "Daily",
    submitted: new Date("2026-07-27T00:00:00Z"),
    status: "Submitted",
    summary:
      "Service mesh upgrade in staging. No production deployments today. Canary tests for payment service running at 5% traffic split.",
  },
  {
    id: 7,
    title: "Weekly Sales Summary — W30",
    author: "Daniel Ruiz",
    department: "Sales",
    type: "Weekly",
    submitted: new Date("2026-07-25T00:00:00Z"),
    status: "Approved",
    summary:
      "Closed $480k ARR this week. Pipeline at $2.1M. Three enterprise deals slipped to August. Renewal rate holding at 94%.",
  },
  {
    id: 8,
    title: "Compliance Audit — Q2",
    author: "Yuki Tanaka",
    department: "Legal",
    type: "Yearly",
    submitted: new Date("2026-07-20T00:00:00Z"),
    status: "Approved",
    summary:
      "Zero critical findings. Two low-severity observations addressed inline. SOC2 Type II audit window opens August 12.",
  },
  {
    id: 9,
    title: "Site Quarterly Maintenance Template — Q2 Audit",
    author: "George (Admin)",
    department: "Engineering",
    type: "Quarterly",
    submitted: new Date("2026-07-28T00:00:00Z"),
    status: "Approved",
    summary:
      "Official Site Quarterly Maintenance Audit Report covering general power plant condition, support structures, PV arrays, indoor/outdoor switchgear, MPPTs, CL/Battery inverters, BESS strings, grid distribution, earthing system, equipment maintenance, and PPE/tool inventories.",
    gveQuarterlyData: createEmptyGveQuarterlyData(),
  },
]
